env_name: "brax:Ant"
agent_name: "PPO"
train_iterations: 5000
callback_freq: 10
# Comment out the seed if you want each run to be different.
seed: 25987700
agent_config:
  rollout_fragment_length: 32
  minibatch_size: 8
  num_devices: 8
  num_envs_per_device: 32
  gamma: 0.97
  lambda_: 0.95
  clip: 0.3
  reward_scaling: 10.0
  entropy_coef: 0.01
  num_epochs: 4
  initial_learning_rate: 0.0003
  final_learning_rate: 0.0003
  network_config:
    hidden_units: [ 32, 32, 32, 32 ]
