env_name: "CartPole"
agent_name: "PPO"
train_iterations: 2000
#seed: 71
agent_config:
  rollout_fragment_length: 32
  minibatch_size: 32
  num_devices: 2
  num_envs_per_device: 4
  gamma: 0.98
  lambda_: 0.8
  entropy_coef: 0.001
  num_epochs: 20
  initial_learning_rate: 0.0005
  learning_rate_decay_steps: 100000
  network_config:
    hidden_units: [ 32, 32 ]
